name: CI external

# trigger
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-ci-external

    - name: Install R
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/'
        sudo apt-get update
        sudo apt-get install r-base

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install redis-server

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .ci_pip_reqs.txt
        pip install rpy2>=3.2.0 cffi>=1.13.1

    - name: Install package
      run: pip install -e .

    - name: Run tests
      run: |
        python -m pytest --cov=pyabc test/external/test_*

    - name: Coverage
      run: codecov -t ${{ secrets.CODECOV_TOKEN }}

