name: CI

# trigger
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Prepare python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-ci-petab

    - name: Install apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install redis-server

    - name: Install amici apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install swig3.0 libatlas-base-dev libhdf5-serial-dev
        sudo ln -s /usr/bin/swig3.0 /usr/bin/swig

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .ci_pip_reqs.txt
        pip install https://github.com/icb-dcm/petab/archive/develop.zip
        pip install -e \
          git+https://github.com/icb-dcm/amici.git@develop#egg=amici\&subdirectory=python/sdist
        git clone --depth 1 \
          https://github.com/petab-dev/petab_test_suite .tmp/petab_test_suite
        pip install -e .tmp/petab_test_suite

    - name: Install package
      run: pip install -e .

    - name: Run tests
      run: |
        python -m pytest --cov=pyabc test/petab/test_*

    - name: Coverage
      run: codecov -t ${{ secrets.CODECOV_TOKEN }}

